# script to plot the results generated by fisher_relationship.py

import matplotlib.pyplot as plt
import csv
import numpy as np

# user parameters
# ---

Sf = 1589   # the number of detected extant species at end
turner = 0.76; brook = 0.74; this_study = 0.34

# where results from fisher relationship stored
# ---

fname_results = '../../results/classical/fisher_relationship/fisher_relationship.csv'


# read in results
# ---

csv_f = csv.reader(open(fname_results))
header = next(csv_f)                        # header order is: omega,N_mean,N_lo,N_hi,nreps
results = [ [ float(v) for v in row ] for row in csv_f ]

omegaV, N_meanV, N_loV, N_hiV, _ = zip(* results )
omegaV = np.array(omegaV); N_meanV = np.array(N_meanV); N_loV = np.array(N_loV); N_hiV = np.array(N_hiV)

# calculate extinction rates
# ----

extn_rate_meanV = (N_meanV-Sf) / N_meanV     # calculate extinction rate
extn_rate_loV = (N_loV-Sf) / N_loV
extn_rate_hiV = (N_hiV-Sf) / N_hiV

plt.plot(omegaV, extn_rate_meanV, 'o-', color='black', label='mean')
#plt.axhline( brook,  ls='dotted', color='black', label='Brook et al. (2003)' )
#plt.axhline( this_study,  ls='dashed', color='black', label='SEUX main result ($\omega=1$)' )
plt.fill_between(omegaV, extn_rate_loV, extn_rate_hiV, facecolor='black', alpha=0.5, label='95% CI')
plt.xlabel('odds ratio of survival probability of undetected versus detected species $\omega$')
plt.ylabel('inferred total extinction rate')
plt.ylim( (0,1) )
#plt.xlim( (0,1) )
plt.grid(True)
plt.legend(loc='best')
plt.tight_layout()
plt.savefig('../../results/classical/fisher_relationship/plot_fisher_relationship.pdf')
plt.close()
# plt.show()
